Ke/clean up package
Laserfiche/lf-js-utils pull request #10
Opened 2022-03-22 15:05 UTC by Ke-Jin-Laserfiche

remove non general-purpose utility methods

2022-03-22 16:29 UTC, alexgomezlf commented on package.json
> +  "exports":  "./dist/index.js"
is this to make it work in node.js?

2022-03-22 16:29 UTC, alexgomezlf commented on src/index.ts
>  export * from './utils/mime-type-utils.js';
do the same thing with MimeTypeUtils, PathUtils, and TimeUtils, UrlUtils

2022-03-22 16:29 UTC, alexgomezlf commented on src/utils/mime-type-utils.ts
> + * @returns the url
maybe move these into a file called IconUtils?

2022-03-22 16:29 UTC, alexgomezlf commented on src/utils/validation-utils/validation-utils-public-api.ts
> +export { evaluateNumericValidationExpression } from './numeric-validation-utils.js';
how does this work when the index.ts then pulls from the individual files?

2022-03-22 19:24 UTC, Ke-Jin-Laserfiche commented on package.json
> +  "exports":  "./dist/index.js"
actually this is not needed. I added this to want it only export from index.js(no sub entry), but not sure anymore if this is needed

2022-03-22 19:28 UTC, Ke-Jin-Laserfiche commented on src/utils/validation-utils/validation-utils-public-api.ts
> +export { evaluateNumericValidationExpression } from './numeric-validation-utils.js';
this is to merge numeric-validation-utils and text-validation-utils's exported functions into one namespace, since they only have one function each.
and the index pull from the public-api as LfMetadataValidationUtils

2022-03-22 19:36 UTC, alexgomezlf requested changes

2022-03-22 19:36 UTC, alexgomezlf commented on DOCUMENTATION.md
>    const originalDateString: string = '2021-03-25';
remove these localization service changes

2022-03-22 19:36 UTC, alexgomezlf commented on src/utils/datetime-utils.ts
> +// TODO make individual methods, export, delete the class
remove TODO

2022-03-22 19:36 UTC, alexgomezlf commented on src/utils/icon-utils.spec.ts
> +import { getDocumentIconIdFromExtension, getDocumentIconUrlFromIconId } from './icon-utils';
change name on line 3 to IconUtils

2022-03-22 19:36 UTC, alexgomezlf commented on src/index.ts
>  export * from './utils/lf-localization.service.js';
export IconUtils?

2022-03-23 16:50 UTC, alexgomezlf commented on src/utils/datetime-utils.spec.ts
> +  it('deserialized datetime is timezone in miliseconds ahead of the original datetime', () => {
what is the difference in these tests.. name is the same

2022-03-23 16:52 UTC, alexgomezlf commented on src/utils/lf-localization.service.ts
> +    try {
remove extra line

2022-03-23 16:54 UTC, alexgomezlf approved these changes

2022-03-23 22:05 UTC, merged