Ke/load resource
Laserfiche/lf-js-utils pull request #9
Opened 2022-03-18 15:30 UTC by Ke-Jin-Laserfiche

update lfLocalizationService to the following interface:

export interface ILocalizationService {
  setLanguage(language: string): void;
  get currentResource(): resourceType | undefined;
  getStringAsync(key: string, params?: string[]): Promise<string>;
  debugMode: boolean;
}

2022-03-18 17:29 UTC, alexgomezlf commented on src/utils/lf-localization.service.ts
> +  constructor(resources?: Map<string, object> | string) {
not optional, has to be one or the other

2022-03-18 17:29 UTC, alexgomezlf commented on src/utils/lf-localization.service.ts
> +    if (this._resources.size > 0 ) {
Okay rethinking this...
this didn't have to change, get should return undefined if doesn't exist so the left is more readable to me

the right assigns the first even if english exists

2022-03-21 17:03 UTC, Ke-Jin-Laserfiche commented on src/utils/lf-localization.service.ts
>    private _currentResource!: resourceType;
it is sometimes undefined. It is usually undefined until getStringAsync, because if _currentResource is undefined, getStringAsync lazy loads the resource as needed and when getStringAsync finds the resource, it sets the resource as _currentResource. what do you think of this implementation?

2022-03-21 19:54 UTC, alexgomezlf requested changes

2022-03-21 19:54 UTC, alexgomezlf commented on src/utils/lf-localization.service.ts
> +      this.setLanguage(this.DEFAULT_LANGUAGE);
oh wait that's public, nevermind

maybe we can change setDefaultLanguage somehow

bc really 
setLanguage is set language we want to get and setDefaultLanguage is set the language that we know will exist

2022-03-21 19:54 UTC, alexgomezlf commented on src/utils/lf-localization.service.ts
> +      const defaultResource = this._resources.get(this.defaultResourceLanguage);
what happens if we haven't gotten the defaultResource yet...

If no defaultResource, then setCurrentResourceAsync with the defaultResourceLanguage... 

but then we might also have to set the selectedLAnguage to the default so that the next time it didn't do the same thing again --- would have to check this, it looks like maybe it would be okay except that it would make an extra call for the selectedLanguage again, but would fall back on line 53 to the cached default the second time

2022-03-21 19:54 UTC, alexgomezlf commented on src/utils/lf-localization.service.ts
> +    let resource = this._resources.get(language);
can we be more specific that Object here or no?

2022-03-23 23:59 UTC, Ke-Jin-Laserfiche commented on src/utils/lf-localization.service.spec.ts
> +  it('getStringAsync assigns default language if specified does not exist', async () => {
these tests do get awaited. https://jestjs.io/docs/asynchronous#asyncawait
if remove await, tests will most likely to fail because resource doesn't exist

2022-03-24 00:37 UTC, alexgomezlf reviewed
First pass review

2022-03-25 16:57 UTC, alexgomezlf requested changes

2022-03-25 16:57 UTC, alexgomezlf commented on src/utils/lf-localization.service.spec.ts
>      lfLocalizationService.setLanguage('nonexistent');
this is same test as below, and should be
"setLanguage does not set currentResource if no resources were passed in constructor and initResourcesFromUrlAsync has not been calles"

2022-03-25 16:57 UTC, alexgomezlf commented on src/utils/lf-localization.service.spec.ts
>      lfLocalizationService.setLanguage('fr-CA');
have a test where you call initResourcesFromUrlAsync and then setLanguage, which does nothing?

2022-03-25 16:57 UTC, alexgomezlf commented on src/utils/lf-localization.service.spec.ts
>      lfLocalizationService.setLanguage('fr-CA');
and one where you call initResourcesFromUrlAsync and then setLanguage, and then initResourcesFromUrlAsync and it will update the currentResource

2022-03-25 16:57 UTC, alexgomezlf commented on src/utils/lf-localization.service.spec.ts
> +    expect(lfLocalizationService.getString(stringKey)).toEqual(expectedString);
this returns key because no map has been specified not becuase no language has been specified. It should return English if no language specified

2022-03-25 16:57 UTC, alexgomezlf commented on src/utils/lf-localization.service.spec.ts
>      lfLocalizationService.setLanguage('es');
the selected language exists, you just haven't called init again yet?

2022-03-25 16:57 UTC, alexgomezlf commented on src/utils/lf-localization.service.spec.ts
> +    lfLocalizationService.setLanguage('zh-Hant');
doesn't setLanguage not do anything after init, unless it's called again?

2022-03-25 16:57 UTC, alexgomezlf commented on src/utils/lf-localization.service.spec.ts
> +    // Assert
formatString should not replace variables if there are no variables to replace
should actually be throw error

2022-03-25 16:57 UTC, alexgomezlf commented on src/utils/lf-localization.service.ts
> +  private _resources: Map<string, object>;
_resources can be undefined.. 

If undefined, that just means they need to call initAsync...

2022-03-25 16:57 UTC, alexgomezlf commented on src/utils/lf-localization.service.ts
> +      const languageWithoutDash: string = this._selectedLanguage.split('-')[0];
only if it's a 404?

2022-03-25 16:57 UTC, alexgomezlf commented on src/utils/lf-localization.service.ts
> +    console.warn(`Selected language resource ${this._selectedLanguage} is not found. Use initResourcesFromUrlAsync to load resource.`);
only need to warn if resources doesn't exist

2022-03-25 16:57 UTC, alexgomezlf commented on src/utils/lf-localization.service.ts
> +      console.warn('Current resource not found. Call setLanguage to set current language.');
call setLanguage isn't applicable. Just say current resource not found

2022-03-25 16:57 UTC, alexgomezlf commented on src/utils/lf-localization.service.ts
> +        console.warn(`Resource '${key}' not found. Use initResourcesFromUrlAsync to load resource.`);
return key?

2022-03-25 16:57 UTC, alexgomezlf commented on src/utils/lf-localization.service.ts
> +    this.setResourceWithFallBack(language);
if !resources, do nothing
if resources, set selected, or selected minus dash, or default.

I think that's what you are doing but want to clarify

2022-03-25 17:04 UTC, Ke-Jin-Laserfiche commented on DOCUMENTATION.md
>  |getString(key: string, params?: string[]): string;  | Gets the translated key using the current selected language. |
if getString cannot find the key, will return << ${key} >>

2022-03-28 17:09 UTC, alexgomezlf commented on src/utils/lf-localization.service.spec.ts
> +  it('should return error', async () => {
should return error when?

2022-03-28 17:09 UTC, alexgomezlf commented on src/utils/lf-localization.service.ts
> +    const setCurrentResourceSuccess = this.setLanguageResource(language);
thisdoesn't make it clear that if there is no map, you won't set currentResource

2022-03-28 23:44 UTC, paolo-arge-lf commented on src/utils/lf-localization.service.ts
> +    this._resources = new Map();
this.resource = undefined;

2022-03-28 23:44 UTC, paolo-arge-lf commented on src/utils/lf-localization.service.ts
> +    url = this.formatUrl(url);
Rename formatUrl to terminateUrlWithSlash

2022-03-28 23:44 UTC, paolo-arge-lf commented on src/utils/lf-localization.service.ts
> +      this.setLanguageResource(this._selectedLanguage);
console.log(`Loaded resource ${url}${this._selectedLanguage}.json.`);

2022-03-28 23:44 UTC, paolo-arge-lf commented on src/utils/lf-localization.service.ts
> +        throw e;
Don't throw just console.error(...)

2022-03-28 23:44 UTC, paolo-arge-lf commented on src/utils/lf-localization.service.ts
> +        throw new ResourceNotFoundError(`Required language resource ${this.DEFAULT_LANGUAGE} is not found.`);
Always log the entire URL

2022-03-28 23:44 UTC, paolo-arge-lf commented on src/utils/lf-localization.service.ts
> +        console.warn('Resource is not found. Cannot set currentResource.');
this._currentResource = undefined;

2022-03-28 23:44 UTC, paolo-arge-lf commented on src/utils/lf-localization.service.spec.ts
>      lfLocalizationService = new LfLocalizationService();
create lfLocalizationService in test Arrange section of the test

2022-03-28 23:44 UTC, paolo-arge-lf commented on src/utils/lf-localization.service.spec.ts
> +    const englishValue: string = '<< NON_EXISTENT_STRING >>';
rename englishValue  -> notFoundValue

2022-03-28 23:44 UTC, paolo-arge-lf commented on src/utils/lf-localization.service.spec.ts
Add test to load from URL  pt-BR, assert you get pt-BR

2022-03-29 00:39 UTC, paolo-arge-lf commented on src/utils/lf-localization.service.ts
> +          console.warn(`Selected language resource ${this._selectedLanguage} is not found at ${url}${this._selectedLanguage}.json.. Fall back to ${languageWithoutDash}.`);
Unify into one console.warn

2022-03-29 17:29 UTC, alexgomezlf approved these changes

2022-03-29 17:32 UTC, merged